---
- name: Crear una organización en vCloud Director
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Crear organización en vCloud Director API
      uri:
        url: "https://172.30.164.36/cloudapi/1.0.0/orgs"
        method: POST
        body_format: json
        body:
          name: "Organizacionrvilela"
          displayName: "pruebarvilela"
          description: "prueba2descripcion"
          isEnabled: true
        headers:
          Accept: "application/json;version=39.0"
          Authorization: "Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhOTNjOWRiOS03NDcxLTMxOTItOGQwOS1hOGY3ZWVkYTg1ZjlAOTg2NTc3YWItMGQ3NS00NDMxLWI4YTctYTJjODhkMDAwNjQyIiwic3ViIjoiYWRtaW5pc3RyYXRvciIsImV4cCI6MTczNDY0NDg5MSwidmVyc2lvbiI6InZjbG91ZF8xLjAiLCJqdGkiOiI0ZWMxZmM2MzJiMzA0ODljOWZmZWEzOTljYWVlMjFhNCJ9.LStxNGzA83NCWQCuI-xhcup5mij5t6rPGTdyeEI-yS4K9E2s9F2tq5OXiWV6GOQSJXVVeG-PZvQUw4YvWGTDHDfm6ktqRXakOd5NQaRBhUwYhqSNVo35AzYNMj9zHSPZAKypolrsaPZoDWjuL6vKrYf4E2ngflR1gL1-51GnFN_qQ9NP6fV19Bc7Gbt9K2xfjEMua6h8PX6XYxHU2kXGLD3MI9_kyIJ2csGu26Z5C90SHPqMO5XTSMYQ5W8ooeBHoEeDZ47CK2A23N0TQdmZ4HTG23_vbgdsMo055y2mBFrDLlZXQNDw5IhrK5fegJvb1ofeLj9VriZtDDlmOpLZ9A"
          Content-Type: "application/json"
        validate_certs: false
      register: response

    - name: Mostrar respuesta de la API
      debug:
        msg: "{{ response }}"

    - name: Validar si la organización se creó correctamente
      assert:
        that:
          - response.status == 201
        msg: "La organización no se creó correctamente. Código de estado: {{ response.status }}"
