---
- name: Crear una organización en vCloud Director
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Crear organización en vCloud Director API
      uri:
        url: "https://cl1env3vcduiod1.umgt1.i.telconet.cloud/cloudapi/1.0.0/orgs"
        method: POST
        body_format: json
        body:
          name: "Organizacionatrujillo"
          fullName: "prueba2atrujillo"
          description: "prueba2descripcion"
          isEnabled: true
        headers:
          Accept: "application/json;version=39.0"
          Authorization: "Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhOTNjOWRiOS03NDcxLTMxOTItOGQwOS1hOGY3ZWVkYTg1ZjlAOTg2NTc3YWItMGQ3NS00NDMxLWI4YTctYTJjODhkMDAwNjQyIiwic3ViIjoiYWRtaW5pc3RyYXRvciIsImV4cCI6MTczNDY0MzI5NiwidmVyc2lvbiI6InZjbG91ZF8xLjAiLCJqdGkiOiIyMzAyNDE5MDY4NzU0ODIxYjAwNDdhZmFmZDcxMzgyZiJ9.eO25CYyqeGaWyQeq1x-5YP3pNDr7Hj3LHxJ6BOQwoDzo59Jxnb8mn1AJKAY5HknZRuu6c2amXEkfI7YzV4DthJQiKNtj02EwUl3UhR9RXWpweDY-hKNetkrUg79DzvWkxiqs8Xr16gy41FgZYhyQyH8dBBwd252s12OX8omIqdkUxtLp69ehIJcmXQPZV5SQgV5LYdwnl1AJMsXNWZk7mT8qtGh2dsuxZEzG2I8grwtLg7HVMDRT7QGfO-YJfQQ13nisAq6FZIVdU8rgrzyT11tI_m1XTHIhEPK93ogDUhhhKeMg0NedMAOkoqBhMt78wGdElbI0i7CXuEQB9Uo5CA"
          Content-Type: "application/json"
        validate_certs: false
      register: response

    - name: Mostrar respuesta de la API
      debug:
        msg: "{{ response }}"
