---
- name: Crear una organización en vCloud desde AWX
  hosts: localhost
  gather_facts: false
  vars:
    vcd_host: "{{ vcloud_host }}"
    vcd_username: "{{ vcloud_username }}"
    vcd_password: "{{ vcloud_password }}"
    vcd_org: "{{ vcloud_org }}"
    vcd_verify_ssl: false
  tasks:
    - name: Crear la organización en vCloud
      community.vmware.vcd_org:
        hostname: "{{ vcd_host }}"
        username: "{{ vcd_username }}"
        password: "{{ vcd_password }}"
        org: "{{ vcd_org }}"
        verify_ssl_certs: "{{ vcd_verify_ssl }}"
        org_name: "{{ org_name }}"
        full_name: "{{ full_name }}"
        is_enabled: false
        state: present
