---
- name: Crear una organización en vCloud Director
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Crear organización en vCloud Director
      vcd_org:
        user: "administrator"
        password: "$D3c3Ui0d_VCD"
        host: "https://172.30.164.36/login/"
        org: "provider"
        verify_ssl_certs: "false"
        state: "present"
        org_name: "vcdOrganizacionatrujillo"
        full_name: "vcdprueba2atrujillo"
        is_enabled: "true"
      delegate_to: localhost
